#Reservated word to create functions -> def

# def say_hello():
#     print("Hello World!")

# #Simple function
# say_hello()

#Creating functions with parameters

def say_hello(name, sex):
    
    sex = sex.lower()
    
    if (sex == "woman"):
        print(f"Hello World, my name is {name} and im {sex}")
    elif (sex == "man"):
        print(f"Hello World, my name is {name} and im {sex}")
    else:
        print(f"Hello World, my name is {name} and im not binary")
    
# say_hello('Manuel', "Man")
# say_hello('Natalia', "Woman")
# say_hello('R2D2', "robot")

#Creating a function with parameters which return values
def generate_random_pwd(num):
    chars = "abcdefghijk"
    integer_number = str(num)
    num = int(integer_number[0])
    char1 = num - 2
    char2 = num
    char3 = num - 5
    pwd = f"{chars[char1]}{chars[char2]}{chars[char3]}{num*2}"
    
    return (pwd, num)

password, first_number = generate_random_pwd(398)
phrase = f"Your new password is {password} which was generated by your num {first_number}"

print(phrase)    
    